// Typed access to the FastAPI backend (types generated by `npm run gen-types`
// from the OpenAPI schema — the Pydantic models stay the single source of
// truth; see src/lib/api-types.d.ts).
//
// Server components call FastAPI directly (absolute URL) forwarding the
// session cookie; client components fetch relative /api/* through the
// next.config.ts rewrite so the cookie stays on one origin. No client cache
// layer and no optimistic UI anywhere: every render shows post-mutation
// truth from SQLite (plan section 4).

import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const API_URL = process.env.API_URL ?? "http://127.0.0.1:8000";

export class ApiError extends Error {
  constructor(public status: number, public detail: unknown) {
    super(typeof detail === "string" ? detail : JSON.stringify(detail));
  }
}

/** Server-component fetch: forwards the session cookie, never caches. */
export async function serverApi<T>(path: string): Promise<T> {
  const cookieStore = await cookies();
  const session = cookieStore.get("nexus_session");
  const response = await fetch(`${API_URL}${path}`, {
    cache: "no-store",
    headers: session ? { cookie: `nexus_session=${session.value}` } : {},
  });
  if (!response.ok) {
    throw new ApiError(response.status, (await response.json()).detail);
  }
  return response.json();
}

/** Like serverApi but returns null on 401/404 instead of throwing. */
export async function serverApiOrNull<T>(path: string): Promise<T | null> {
  try {
    return await serverApi<T>(path);
  } catch (err) {
    if (err instanceof ApiError && (err.status === 401 || err.status === 404)) {
      return null;
    }
    throw err;
  }
}

/** Client-portal pages call this FIRST, before any data fetch: layouts and
 * pages render concurrently in the App Router, so a page must do its own
 * auth/role gate rather than relying on the layout's redirect winning the
 * race (a platform_admin hitting a client page would otherwise 403 on the
 * data fetch and 500 the RSC stream). */
export async function requireClientUser(): Promise<Me> {
  const me = await serverApiOrNull<Me>("/auth/me");
  if (!me) redirect("/login");
  if (me.role === "platform_admin") redirect("/admin");
  return me;
}

// ---- shared row shapes used by the screens (trimmed views of api-types) ----

export type Me = {
  user_id: number;
  email: string;
  display_name: string;
  role: "platform_admin" | "client_admin" | "member";
};

export type ProjectSummary = {
  project_id: number;
  name: string;
  status: string;
  paused_reason: string | null;
  timeline_start: string | null;
  timeline_end: string | null;
  budget_total: number | null;
};

export type Task = {
  task_id: number;
  phase_id: number;
  title: string;
  status: string;
  effort_hours: number | null;
  owner_id: number | null;
  owner_name: string | null;
  planned_start: string | null;
  planned_end: string | null;
  actual_start: string | null;
  actual_end: string | null;
  percent_complete: number | null;
  slack_days: number | null;
  on_critical_path: number;
  unassignable: number;
  needs_clarification: string | null;
  skill_tags: string[];
};

export type Phase = {
  phase_id: number;
  name: string;
  description: string;
  planned_start: string;
  planned_end: string;
  status: string;
  sequence_order: number;
  needs_clarification: string | null;
};

export type ProjectDetail = ProjectSummary & {
  scope_document: string | null;
  config_overrides: Record<string, unknown>;
  phases: Phase[];
  tasks: Task[];
  dependencies: { predecessor_task_id: number; successor_task_id: number }[];
};

export type ReviewItem = {
  item_id: number;
  project_id: number;
  tier: 1 | 2 | 3;
  item_type: string;
  payload: Record<string, unknown>;
  created_by_skill: string;
  status: string;
  resolved_by: number | null;
  resolved_at: string | null;
  reviewer_notes: string | null;
  created_at: string;
  escalation_stages: {
    stage: string;
    reason: string;
    outcome: string | null;
    occurred_at: string;
  }[];
};
